server:
  port: 8011
spring:
  application:
    name: consumer-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO 
